[package]
name = "sr-book-cn"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["kiritan"]
license = "CC BY-NC-SA"
description = "An unofficial Chinese translation of Symphonic Rain."
repository = "https://github.com/kiritantakechi/sr-book-cn"
keywords = ["typst", "book", "symphonic rain", "translation", "chinese"]
categories = ["book"]
exclude = ["imgs"]

[template]
path = "template"
entrypoint = "book.typ"
thumbnail = "thumbnail.png"
